version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      gha-all:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    auto-merge: true
